### PR TITLE
Semantic highlighting for XPath expressions

### LINKED ISSUE #123: Add XPath Color Segmentation
Update language extension to add XPath Color Segmentation:
- Stems from https://github.com/apache/daffodil-vscode/pull/117#discussion_r883745861

### PR DESCRIPTION
**Pull request by michael-hoke**
Closes #123

### CODE REVIEW

**Comment by scholarsmate** [comment]
@michael-hoke, this looks ready, but you'll have to squash the commit.

**Comment by michael-hoke** [comment]
Will squash and run through CI again once it's approved.

**Comment by nlewis05** [comment]
+1

**Review by scholarsmate — APPROVED** [review]
+1

**Comment by scholarsmate** [comment]
@michael-hoke, I fixed a merge conflict in `yarn.lock`.  It needs to be resquashed.

**Comment by michael-hoke** [comment]
@scholarsmate Up to date with current main.

**Pull request merged**
