### PR TITLE
update omega-edit from 0.9.34 to 0.9.39 for an important fixes

### PR DESCRIPTION
**Pull request by scholarsmate**
This version has an important bug fix related to the RPC server not finding the main class in some cases.  This also introduces a new iterative replace function that will be needed for the Data Editor.

### CODE REVIEW

**Review by Shanedell — APPROVED** [review]
+1 👍

**Comment by scholarsmate** [comment]
@stevedlawrence, will you review this PR at your earliest convenience?  Thanks!

**Comment by scholarsmate** [comment]
Hold off on merging this as there was a bug found/fixed for clearing session edits that will need to be published as a new version and we're going to need that fix for the Data Editor.

**Review by arosien — APPROVED** [review]
👍

**Pull request merged**
