### PR TITLE
Multiple CI updates

### LINKED ISSUE #772: Add CI build matrix for JVM versions
This will help tease out issues like JVM reflection, etc.

### PR DESCRIPTION
**Pull request by shanedell**
Multiple CI updates:

- Add matrix to test different Java versions to main CI and nightly CI.
- Cleaned up the CI workflow file a bit.
  - The steps were too compacted, believe new layout makes it easier to read and follow.
- Add java_version to job names.
- Remove sbt compile from windows jobs, seemed to cause windows issues with jaxb.
- Believe the nightly CI maybe fixed with this update.
- Possibly fixes https://github.com/apache/daffodil-vscode/issues/855 but will wait to see if a nightly build passes before closing.

Closes https://github.com/apache/daffodil-vscode/issues/772

### CODE REVIEW

**Review by mbeckerle — APPROVED** [review]
Looks like your matrix is only Java 8. 

Daffodil library tests on 8, 11, 17 
(Not yet Java 21, though that is now released)

BTW: 17 is noticeably faster.

**Comment by shanedell** [comment]
> Looks like your matrix is only Java 8. 
> 
> Daffodil library tests on 8, 11, 17 
> (Not yet Java 21, though that is now released)
> 
> BTW: 17 is noticeably faster. 
> 

Yeah I think you might be looking at a different job. The ratCheck and lint only uses Java 8 I think but if you look at the package and test step it has Java 8, 11 and 17.

**Comment by scholarsmate** [comment]
The matrix'ed build looks good to me in general.  The matrix for the code format and rat checks is a bit overkill since we're only running one configuration for those (Java 8) jobs. Do you foresee adding more OSes, Node versions, or Java versions to these jobs?  I don't.


I'll re-review when it passes CI.

**Comment by shanedell** [comment]
@scholarsmate I mostly did this as it is the way done in Daffodil. I also thought it made a bit easier to know where you can change the versions at. Currently the CI will not pass till #895 is completed.

**Review by scholarsmate — APPROVED** [review]
+1, LGTM.

**Pull request merged**
