### PR TITLE
Updated package.json to use Daffodil 3.8.0

### LINKED ISSUE #1052: Update to Apache Daffodil 3.8.0
We are currently using version 3.7.0, Version 3.8.0 just was approved to release on 6/14/24, we should update our package and ensure functionally of the extension is still stable in our 1.4.0 release

### PR DESCRIPTION
**Pull request by rthomas320**
Update to Daffodil 3.8.0
Closes #1052

### CODE REVIEW

**Review by scholarsmate — APPROVED** [review]
+1

**Review by hdalsania — APPROVED** [review]
+1 - I tested this PR and everything is working as expected on Windows and RHEL9 OSes. I performed basic IntelliSense, hover functionality, Data Editor, profiler, TDML functionality and debugging a schema. It all worked out as expected.

**Review by shanedell — APPROVED** [review]
+1 👍 Wait to merge till @stricklandrbls also approves he is doing some additional testing on Mac.

**Review by stricklandrbls — APPROVED** [review]
+1
Tested on an M1 series Macbook and everything worked fine.

**Pull request merged**
