### PR TITLE
Multiple components on a line

### PR DESCRIPTION
**Pull request by rt320**

### CODE REVIEW

**Comment by stevedlawrence** [comment]
This looks like it contains fixes that are already included in PR #294 (in fact, it's hard to tell what isn't actually part of that). Can you fix the conflicts in that PR and force push, then this PR can be fixed so it only includes relevant changes.

**Comment by rt320** [comment]
I did a hard reset to master. Some (all?) of the changes for pr #294 are missing.  I still have my code for that change, as well as the current changes. But I don't know how to merge in the missing changes from pr #294 and this change in a single commit.

**Comment by rt320** [comment]
For example this change is not in main
image

**Comment by stevedlawrence** [comment]
I can see it fine. Maybe you have a search filter? You can also click on the #294 link that github automatically adds when referenced.

**Comment by scholarsmate** [comment]
Rebased this PR on asf/main, fixed up merge conflicts and lints, and squashed in PR #309.

**Pull request closed without merging**
