### PR TITLE
Update LICENSE to match part of bin.LICENSE

### PR DESCRIPTION
**Pull request by tuxji**
LICENSE: Update slightly so that any text in common between LICENSE
and build/bin.LICENSE matches exactly in both files.

Additional work for #97 (RC2 Updates)

### CODE REVIEW

**Comment by tuxji** [comment]
I've just forked the repository so I won't push to the main repository by mistake again.  I'll delete my branch after the PR's merged.

**Review by stevedlawrence — APPROVED** [review]
+1

**Comment by tuxji** [comment]
Still need someone to give this PR a second +1.

**Review by scholarsmate — APPROVED** [review]

**Comment by arosien** [comment]
+1

**Pull request merged**
