### PR TITLE
Fixes Alignment of Viewport Header Byte Texts

### LINKED ISSUE #864: Unaligned Viewport Data Byte Offset Text
The viewport byte offset text displayed does not align with the individual bytes of data for systems with higher than average resolution / dpi (2K, 4K, etc..).

Each byte offset set should be individualized similar to how each byte of data, given that the viewport data table headers should always be the same width as the rows of data.

<details><summary><b>Screenshot</b></summary>

artifact-dfdl-dataeditor

</details>

**Note:** This only seems to happen if the data editor is initialized for data editor `<body>` widths that do not trigger the element collapsing effect (1,500px). This artifact is resolved if initially the window size > 1500px and is then shrunk to trigger the `shouldCollapse` condition. Even if the window is explanded to be larger than the width threshold.

<details><summary><b>Screenshot</b></summary>

artifact-dfdl-dataeditor-fix

</details>

### PR DESCRIPTION
**Pull request by stricklandrbls**
- Fixed alignment of viewport byte indexing text.

Closes #864

### CODE REVIEW

**Comment by scholarsmate** [comment]
@stricklandrbls, can you post screenshots of the fixed headers?

**Comment by scholarsmate** [comment]
The alignment looks good.  IIRC, the header content used to be bold.  It would be good if the header stood out a bit more from the content.  Maybe a different background color?

**Review by shanedell — APPROVED** [review]
+1

**Comment by stricklandrbls** [comment]
This PR had been up for too long and I needed the correction in order to complete development towards #797. That being said I'm going to close this PR as I rebased the branch for #797 on top of this branch so it includes this resolution.

**Pull request closed without merging**
