### PR TITLE
Adjusted file metrics fieldset for long file paths

### LINKED ISSUE #543: Increase Width of Data Editor Top Configuration Panel
If a user has opened a file with an exceptionally long filepath, the visibility within that panel becomes distorted. This can be resolved by increasing the width of the top panel or the header section.

### PR DESCRIPTION
**Pull request by stricklandrbls**
- Increased width sizes and reworked the css to overflow text in a more appropriate manner.

Close #543

### CODE REVIEW

**Review by scholarsmate — APPROVED** [review]
+1 👍.  I've tested this and it looks good to me.

**Comment by scholarsmate** [comment]
This change spreads out the controls so it looks like this:
Screenshot 2023-03-31 at 3 01 43 PM

**Comment by Shanedell** [comment]
@stricklandrbls I will approve once the formatting it fixed.

**Comment by stricklandrbls** [comment]
> @stricklandrbls I will approve once the formatting is fixed.

@Shanedell Fixed.

**Review by Shanedell — APPROVED** [review]
+1 👍

**Pull request merged**
