### PR TITLE
Support JDK 17 + JAXB reflection at runtime.

### LINKED ISSUE #745: JDK 17 not supported when running TDML actions
While #699 fixes _builds_ of the debugger backend, adding the JVM reflection flags is missing when the extension _launches_ the debugger and subsequent TDML actions trigger the JVM reflection bug.

The extension needs to either
- detect what JVM version will be used, and add the flags to the command line; or
- add an extension setting, say "Use JDK 17 settings", so the extension can provide the flags.

Until this is available we should have a FAQ entry, or something, that talks about JVM 17 issues like this.

### PR DESCRIPTION
**Pull request by arosien**
Fixes #745.

- JDK 17 is detected at build time to enable the jvm flags during tests.
- Use the locate-java-home npm module to detect the latest JVM version from within the extension, honoring `$JAVA_HOME` if set.

### CODE REVIEW

**Review by scholarsmate — APPROVED** [review]
+1

**Review by shanedell — APPROVED** [review]
+1

**Comment by scholarsmate** [comment]
Conflicts resolved.  Now they need to be squashed.

**Comment by shanedell** [comment]
@scholarsmate @stricklandrbls There seems to be an issue with `clearInterval` in this PR, do either of you know why?

**Comment by scholarsmate** [comment]
@shanedell, there is a type disagreement on the timer.  Wonder why it's affecting this PR and not happening elsewhere?  I'll look more into this Timer.

**Comment by arosien** [comment]
> 

I think it is from a bad merge with yarn.lock. I'll try to fix.

**Comment by arosien** [comment]
> 

Not that, but I can fix the typescript types real quick `Timer => Timeout`.

**Pull request merged**
