### PR TITLE
Fix DeltaXML Licensing

### LINKED ISSUE #735: DeltaXML licensing is incorrect
The LICENSE file lists DeltaXML as a MIT licensed, but all the files listed as being from delta XML have ASF headers.

- src/language/semantics/dfdlExt.ts
- src/language/semantics/documentChangeHandler.ts
- src/language/semantics/functionData.ts
- src/language/semantics/xPathDocumentChangeHandler.ts
- src/language/semantics/xpLexer.ts
- src/language/semantics/xslLexer.ts
- src/language/semantics/xsltTokenDiagnostics.ts

You cannot change the license of a file, these files should have a MIT header.

Further, I believe these files are includes in the .vsix file and so must also be mentioned the the package/build LICENSE file.

### PR DESCRIPTION
**Pull request by michael-hoke**
Closes #735

### CODE REVIEW

**Review by shanedell — APPROVED** [review]
+1 👍

**Review by scholarsmate — APPROVED** [review]
+1

**Comment by shanedell** [comment]
@michael-hoke Please rebase off the latest changes to main and fix the merge conflicts. Once this is done I can merge this in.

**Comment by michael-hoke** [comment]
@shanedell Fixed merge conflict and rebased

**Pull request merged**
