### PR TITLE
Pin package rollup-plugin-multi-input to 1.3.2

### PR DESCRIPTION
**Pull request by Shanedell**

### CODE REVIEW

**Review by NolanMatt — APPROVED** [review]
👍 But in grey

**Comment by scholarsmate** [comment]
Rollup-plugin-multi-input version 1.3.3 is a development dependency that required node 16+, so we pinned it at 1.3.2 so that node 14 builds will still work.

**Comment by Shanedell** [comment]
@arosien Can you give this a look over when you have a chance? This is causing all of the current PRs to fail CI because as Davin mentioned it is trying to install a newer version that required nodejs 16.

**Review by arosien — APPROVED** [review]
👍

**Pull request merged**
