### PR TITLE
Support Java 8

### LINKED ISSUE #16: Restructure Scala code to support JDK 8
Follow up to https://github.com/jw3/example-daffodil-vscode/issues/94:

@arosien said

- Daffodil required JDK 8, so we could try to also support it
- We currently need JDK 11 to support use of Path.of, which could perhaps be replaced with something available in older JVMs.
- Nested object in Scala isn't supported until JDK 9 or greater.

Original issue https://github.com/jw3/example-daffodil-vscode/issues/136

### PR DESCRIPTION
**Pull request by stevedlawrence**
Closes #16

### CODE REVIEW

**Review by mbeckerle — APPROVED** [review]
+1

**Comment by jw3** [comment]
The nio changes are good but the nested object issue in #16 remains.

**Comment by stevedlawrence** [comment]
These changes allow building on Java 8, but due to issue #16, it still fails to run on Java 8. We can still build on Java 8 as long as we run on Java 9+. Maybe we can change our build requirements to Java 8+ but run requirements to Java 9+?

**Comment by jw3** [comment]
That sounds fine to me.

**Review by jw3 — APPROVED** [review]
+1 for build on 8 run on 9 until we can address the nested object issue

**Pull request merged**
