### PR TITLE
Update package.json version in preperation for 1.1.0 release vote

### PR DESCRIPTION
**Pull request by Shanedell**

### CODE REVIEW

**Comment by stevedlawrence** [comment]
We need to have a DISCUSS thread open for 72 hours to determine if it's the right time for a release and if anything should be included in this release.

**Comment by scholarsmate** [comment]
The roadmap is here: https://github.com/apache/daffodil-vscode/wiki/Roadmap-for-the-Apache-Daffodil-VS-Code-Extension

The issues that fall under the 1.1.0 milestone are here: https://github.com/apache/daffodil-vscode/milestone/2

Completion of milestone 1.2.0 is planned for release this month.

**Review by tuxji — APPROVED** [review]
+1

**Comment by Shanedell** [comment]
@stevedlawrence IS this good to go now since that DISCUSSION was created and has been open longer than 72 hours? Is it good to move forward with it as you were the only who replied and gave a +1 and the new updates to the release candidate have been merged into main for `apache/daffodil`?

**Review by stevedlawrence — APPROVED** [review]
+1 Yep, looks good to me

**Pull request merged**
