### PR TITLE
Data Editor Reacts to launch.json Changes

### LINKED ISSUE #930: Data Editor Log Level Not Honoring Changes
On Windows 11, when the `launch.json` config is edited to contain a data editor log level of `debug`, the data editor does not ever update the default log level of `info`.

data-editor-log-not-debug

### PR DESCRIPTION
**Pull request by stricklandrbls**
- Implemented reactive parsing of `.vscode/launch.json`

Closes #930

### CODE REVIEW

**Review by shanedell — APPROVED** [review]
+1 👍

**Review by nlewis05 — APPROVED** [review]
image

**Review by rthomas320 — APPROVED** [review]

**Review by scholarsmate — APPROVED** [review]
+1, LGTM.

**Review by hdalsania — APPROVED** [review]
+1

I can see debug messages now.

**Pull request merged**
